# Additional labels to add to the cronjob
cronLabels: {}
  #key: "value"

image:
  repository: ryaneorth/scheduled-volume-snapshotter
  #tag: latest
  # List of secrets used to authorize against the remote repo
  # - name: docker-auth-secret
  imagePullSecrets: []
  pullPolicy: IfNotPresent

nameOverride: ""

schedule: "*/15 * * * *"

successfulJobsHistoryLimit: 3
failedJobsHistoryLimit: 1

rbac:
  enabled: true

logLevel: INFO

ignoreUnsuccessfulSnapshots: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Additional annotations to add to the pod
podAnnotations: {}
  #key: "value"

# Additional labels to add to the pod
podLabels: {}
  #key: "value"

# Pod level security context
# https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
podSecurityContext: {}

# Container level security context
# https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
containerSecurityContext: {}

snapshotClasses: []
  # List of VolumeSnapshotClass
  #- metadata:
  #    name: my-snapshotclass
  #  parameters:
  #    storage-locations: us-east2
  #  driver: pd.csi.storage.gke.io
  #  deletionPolicy: Delete

snapshots: []
  # List of ScheduledVolumeSnapshot
  #- metadata:
  #    name: my-snapshot
  #    namespace: my-namespace
  #  spec:
  #    snapshotClassName: my-snapshotclass
  #    persistentVolumeClaimName: my-pvc
  #    snapshotFrequency: 1d
  #    snapshotRetention: 365d
  #    snapshotLabels:
  #      firstLabel: someLabelValue
  #      secondLabel: anotherLabelValue

startingDeadlineSeconds: 300
